### ISSUE TITLE
[Bug]: probleem bij het wegschrijven ow.nc door gebruik tempfile library

### ISSUE THREAD

**Issue by tberends** [nens/fews-3di#28]
### Contact Details

thomas.berends@nelen-schuurmans.nl

### Complexity

moderate

### Priority

high prio

### What happened?

**Code** 
Issue in regel 360-361 van https://github.com/nens/fews-3di/blob/master/fews_3di/utils.py

**Probleem**
Op een Windowsmachine is de kopieeractie van de tempfile op tempdirectory (C:) naar de output directory (D:) niet toegestaan tussen diskdrives, zie:

DEBUG: Wrote new time-index-only netcdf to C:\Users\tberends\AppData\Local\Temp\fews-3di8ztj0y_0\ow.nc
Traceback (most recent call last):
  File "D:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\3Di64\venv\Scripts\run-fews-3di.exe\__main__.py", line 7, in <module>
  File "D:\3Di64\venv\lib\site-packages\fews_3di\scripts.py", line 80, in main
    threedi_simulation.run()
  File "D:\3Di64\venv\lib\site-packages\fews_3di\simulation.py", line 177, in run
    self._process_results()
  File "D:\3Di64\venv\lib\site-packages\fews_3di\simulation.py", line 626, in _process_results
    converted_netcdf.replace(open_water_output_file)
  File "D:\Python39\lib\pathlib.py", line 1395, in replace
    self._accessor.replace(self, target)

OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\tberends\\AppData\\Local\\Temp\\fews-3di8ztj0y_0\\ow.nc' -> 'output\\ow.nc'

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by reinout** [comment]
Het probleem zit elders, zie de fix in https://github.com/nens/fews-3di/pull/29/files

Die is als je het heeeeeeel snel nodig hebt met het handje te doen, het zijn twee regels. Als het goed is fixt het dat.
